# Testing normal usage STD_CAN with std_frame
protocol = "can"
name = "elec_skin"

can_interface = "can0"
extended_frame = true
canfd_enable = false
timeout_us = 1234567


[[cmd]]
description = ""
cmd_name = "model_on"
can_id = "0x0e802f00"
ctrl_len = 1
ctrl_data = ["0x00"]

[[cmd]]
description = "body middle"
cmd_name = "body_middle"
can_id = "0x0e802000"
ctrl_len = 1
ctrl_data = ["0x00"]

[[cmd]]
description = "left back leg"
cmd_name = "left_back_leg"
can_id = "0x0e802100"
ctrl_len = 1
ctrl_data = ["0x00"]

[[cmd]]
description = ""
cmd_name = "body_left"
can_id = "0x0e802200"
ctrl_len = 1
ctrl_data = ["0x00"]

[[cmd]]
description = ""
cmd_name = "left_front_leg"
can_id = "0x0e802300"
ctrl_len = 1
ctrl_data = ["0x00"]

[[cmd]]
description = ""
cmd_name = "front_chest"
can_id = "0x0e802400"
ctrl_len = 1
ctrl_data = ["0x00"]

[[cmd]]
description = ""
cmd_name = "right_front_leg"
can_id = "0x0e802500"
ctrl_len = 1
ctrl_data = ["0x00"]

[[cmd]]
description = ""
cmd_name = "body_right"
can_id = "0x0e802600"
ctrl_len = 1
ctrl_data = ["0x00"]

[[cmd]]
description = ""
cmd_name = "right_back_leg"
can_id = "0x0e802700"
ctrl_len = 1
ctrl_data = ["0x00"]