[[step]]
mode = 12
gait_id = 1
contact = 0
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.225,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 5000

[[step]]
mode = 3
gait_id = 3
contact = 15
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ -0.12, 0.0, 0.0,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 1000

[[step]]
mode = 11
gait_id = 81
contact = 30
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.0, 0.0, 1.0,]
foot_pose = [ 0.0, -0.02, 0.0, 0.02, 0.0, 0.0,]
step_height = [ 35035.0, 20020.0,]
value = 0
duration = 420

[[step]]
mode = 11
gait_id = 81
contact = 30
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.0, 0.0, 1.0,]
foot_pose = [ 0.0, 0.02, 0.0, -0.02, 0.0, 0.0,]
step_height = [ 35035.0, 20020.0,]
value = 0
duration = 420

[[step]]
mode = 11
gait_id = 81
contact = 30
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.0, 0.0, 1.0,]
foot_pose = [ 0.0, -0.02, 0.0, 0.02, 0.0, 0.0,]
step_height = [ 35035.0, 20020.0,]
value = 0
duration = 420

[[step]]
mode = 11
gait_id = 81
contact = 30
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.0, 0.0, 1.0,]
foot_pose = [ 0.0, 0.02, 0.0, -0.02, 0.0, 0.0,]
step_height = [ 35035.0, 20020.0,]
value = 0
duration = 420

[[step]]
mode = 11
gait_id = 81
contact = 30
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.0, 0.0, 1.0,]
foot_pose = [ 0.0, -0.02, 0.0, 0.02, 0.0, 0.0,]
step_height = [ 35035.0, 20020.0,]
value = 0
duration = 420

[[step]]
mode = 11
gait_id = 81
contact = 30
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.0, 0.0, 1.0,]
foot_pose = [ 0.06, 0.0, 0.06, 0.0, 0.0, 0.0,]
step_height = [ 35035.0, 20020.0,]
value = 0
duration = 660

[[step]]
mode = 3
gait_id = 3
contact = 15
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.11, 0.0, 0.0,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 1000

[[step]]
mode = 16
gait_id = 0
contact = 0
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 790

[[step]]
mode = 21
gait_id = 5
contact = 0
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.225,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 500

[[step]]
mode = 3
gait_id = 3
contact = 15
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 500

[[step]]
mode = 11
gait_id = 84
contact = 40
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 50.0, 50.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.04, 0.0, 1.0,]
foot_pose = [ 0.04, 0.0, 0.01, 0.0, 0.01, 0.0,]
step_height = [ 10060.0, 60010.0,]
value = 1
duration = 240

[[step]]
mode = 11
gait_id = 84
contact = 40
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 50.0, 50.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.04, 0.0, 1.0,]
foot_pose = [ 0.04, 0.0, -0.02, 0.0, -0.02, 0.0,]
step_height = [ 10060.0, 60010.0,]
value = 1
duration = 240

[[step]]
mode = 11
gait_id = 84
contact = 40
life_count = 0
vel_des = [ -0.05, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 50.0, 50.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.01, 0.0, 1.0,]
foot_pose = [ 0.01, 0.0, 0.04, 0.0, 0.04, 0.0,]
step_height = [ 60010.0, 10060.0,]
value = 1
duration = 240

[[step]]
mode = 11
gait_id = 84
contact = 40
life_count = 0
vel_des = [ -0.05, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 50.0, 50.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ -0.02, 0.0, 1.0,]
foot_pose = [ -0.02, 0.0, 0.04, 0.0, 0.04, 0.0,]
step_height = [ 60010.0, 10060.0,]
value = 1
duration = 240

[[step]]
mode = 11
gait_id = 84
contact = 40
life_count = 0
vel_des = [ -0.05, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 50.0, 50.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.04, 0.0, 1.0,]
foot_pose = [ 0.04, 0.0, 0.01, 0.0, 0.01, 0.0,]
step_height = [ 10060.0, 60010.0,]
value = 1
duration = 240

[[step]]
mode = 11
gait_id = 84
contact = 40
life_count = 0
vel_des = [ -0.05, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 50.0, 50.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.04, 0.0, 1.0,]
foot_pose = [ 0.04, 0.0, -0.02, 0.0, -0.02, 0.0,]
step_height = [ 10060.0, 60010.0,]
value = 1
duration = 240

[[step]]
mode = 11
gait_id = 84
contact = 40
life_count = 0
vel_des = [ -0.05, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 50.0, 50.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.01, 0.0, 1.0,]
foot_pose = [ 0.01, 0.0, 0.04, 0.0, 0.04, 0.0,]
step_height = [ 60010.0, 10060.0,]
value = 1
duration = 240

[[step]]
mode = 11
gait_id = 84
contact = 40
life_count = 0
vel_des = [ -0.05, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 50.0, 50.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ -0.02, 0.0, 1.0,]
foot_pose = [ -0.02, 0.0, 0.04, 0.0, 0.04, 0.0,]
step_height = [ 60010.0, 10060.0,]
value = 1
duration = 240

[[step]]
mode = 11
gait_id = 84
contact = 40
life_count = 0
vel_des = [ -0.05, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 50.0, 50.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.04, 0.0, 1.0,]
foot_pose = [ 0.04, 0.0, 0.01, 0.0, 0.01, 0.0,]
step_height = [ 10060.0, 60010.0,]
value = 1
duration = 240

[[step]]
mode = 11
gait_id = 84
contact = 40
life_count = 0
vel_des = [ -0.05, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 50.0, 50.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.04, 0.0, 1.0,]
foot_pose = [ 0.04, 0.0, -0.02, 0.0, -0.02, 0.0,]
step_height = [ 10060.0, 60010.0,]
value = 1
duration = 240

[[step]]
mode = 11
gait_id = 84
contact = 40
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 50.0, 50.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.01, 0.0, 1.0,]
foot_pose = [ 0.01, 0.0, 0.04, 0.0, 0.04, 0.0,]
step_height = [ 60010.0, 10060.0,]
value = 1
duration = 240

[[step]]
mode = 11
gait_id = 84
contact = 40
life_count = 0
vel_des = [ -0.05, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 50.0, 50.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ -0.02, 0.0, 1.0,]
foot_pose = [ -0.02, 0.0, 0.04, 0.0, 0.04, 0.0,]
step_height = [ 60010.0, 10060.0,]
value = 1
duration = 240

[[step]]
mode = 11
gait_id = 84
contact = 40
life_count = 0
vel_des = [ -0.05, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 50.0, 50.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.04, 0.0, 1.0,]
foot_pose = [ 0.04, 0.0, 0.01, 0.0, 0.01, 0.0,]
step_height = [ 10060.0, 60010.0,]
value = 1
duration = 240

[[step]]
mode = 11
gait_id = 84
contact = 40
life_count = 0
vel_des = [ -0.05, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 50.0, 50.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ 0.04, 0.0, 1.0,]
foot_pose = [ 0.04, 0.0, -0.02, 0.0, -0.02, 0.0,]
step_height = [ 10060.0, 60010.0,]
value = 1
duration = 240

[[step]]
mode = 11
gait_id = 84
contact = 40
life_count = 0
vel_des = [ -0.05, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 50.0, 50.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ -0.005, 0.0, 1.0,]
foot_pose = [ -0.005, 0.0, 0.0, -0.005, 0.0, -0.005,]
step_height = [ 60010.0, 10060.0,]
value = 1
duration = 240

[[step]]
mode = 11
gait_id = 84
contact = 40
life_count = 0
vel_des = [ -0.05, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 50.0, 50.0, 1.0, 1.0, 1.0, 1.0,]
ctrl_point = [ -0.005, 0.0, 1.0,]
foot_pose = [ -0.005, 0.0, 0.0, -0.005, 0.0, -0.005,]
step_height = [ 60010.0, 10060.0,]
value = 1
duration = 240

[[step]]
mode = 21
gait_id = 5
contact = 0
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.225,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 300

[[step]]
mode = 16
gait_id = 4
contact = 0
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 920

[[step]]
mode = 21
gait_id = 5
contact = 0
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.225,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 500

[[step]]
mode = 3
gait_id = 3
contact = 15
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 500

[[step]]
mode = 11
gait_id = 69
contact = 0
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 600

[[step]]
mode = 11
gait_id = 68
contact = 0
life_count = 0
vel_des = [ 0.0, -0.01, 0.3,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 4500

[[step]]
mode = 11
gait_id = 69
contact = 0
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 600

[[step]]
mode = 21
gait_id = 5
contact = 0
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.225,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 300

[[step]]
mode = 16
gait_id = 2
contact = 0
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 840

[[step]]
mode = 21
gait_id = 5
contact = 0
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.225,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 5000

