# OFF，急停
[[motion_ids]]
motion_id = 0     
map = [0, 0]     
pre_motion = [0]
post_motion = [0]

# 高阻尼趴下
[[motion_ids]]
motion_id = 101
map = [7, 0]    
pre_motion = [1, 3]
post_motion = [101]

# 高阻尼趴下
[[motion_ids]]
motion_id = 102
map = [8, 0]    
pre_motion = [1, 3]
post_motion = [102]

# 恢复站立
[[motion_ids]]
motion_id = 111
map  = [12, 0]   
pre_motion = [1, 3]
post_motion = [111]

# 后空翻
[[motion_ids]]
motion_id = 121
map  = [5, 0]   
pre_motion = [1, 3]
post_motion = [121]

# 前空翻
[[motion_ids]]
motion_id = 122
map  = [14, 0]   
pre_motion = [1, 3]
post_motion = [122]

# 作揖
[[motion_ids]]
motion_id = 123
map  = [64, 0]   
pre_motion = [1, 3]
post_motion = [123]

# 向左侧躺下后恢复站立，向左打滚一圈
[[motion_ids]]
motion_id = 124
map  = [12, 17]   
pre_motion = [1, 3]
post_motion = [124]

# 绝对量力控姿态,保证崎岖地面能够站立，绝对量力控
[[motion_ids]]
motion_id = 201
map = [3, 0]    
pre_motion = [1, 3]
post_motion = [201]

# 增量力控姿态,保证崎岖地面能够站立，增量力控
[[motion_ids]]
motion_id = 202
map = [3, 3]    
pre_motion = [1, 3]
post_motion = [202]

# 位控姿态-相对姿态
[[motion_ids]]
motion_id = 211
map = [21, 0]   
pre_motion = [1, 3]
post_motion = [211]

# 位控姿态-站立
[[motion_ids]]
motion_id = 212
map = [21, 5]   
pre_motion = [1, 3]
post_motion = [212]

# 前后跳
[[motion_ids]]
motion_id = 301
map  = [11, 1]   
pre_motion = [1, 3]
post_motion = [301]

# 四足小跳
[[motion_ids]]
motion_id = 302
map  = [11, 2]   
pre_motion = [1, 3]
post_motion = [302]

# 自变频行走
[[motion_ids]]
motion_id = 303
map = [11, 3]  
pre_motion = [111, 201, 211]
post_motion = [303]

# 遛狗
[[motion_ids]]
motion_id = 304
map = [11, 4]   
pre_motion = [1, 3]
post_motion = [304]

# 快跑
[[motion_ids]]
motion_id = 305
map = [11, 5]   
pre_motion = [1, 3]
post_motion = [305]
