# OFF，急停
[[motion_ids]]
motion_id = 0     
map = [0, 0]     
pre_motion = [1, 3]
post_motion = [1, 3]

# 力控姿态,保证崎岖地面能够站立，增量力控
[[motion_ids]]
motion_id = 1
map = [3, 3]    
pre_motion = [1, 3]
post_motion = [1, 3]

# 高阻尼趴下
[[motion_ids]]
motion_id = 2
map = [7, 0]    
pre_motion = [1, 3]
post_motion = [1, 3]

# 自变频行走
[[motion_ids]]
motion_id = 3
map = [11, 3]  
pre_motion = [1, 3]
post_motion = [1, 3]

# 遛狗
[[motion_ids]]
motion_id = 4
map = [11, 4]   
pre_motion = [1, 3]
post_motion = [1, 3]

# 快跑
[[motion_ids]]
motion_id = 5
map = [11, 5]   
pre_motion = [1, 3]
post_motion = [1, 3]

# 四足小跳
[[motion_ids]]
motion_id = 6
map  = [11, 2]   
pre_motion = [1, 3]
post_motion = [1, 3]

# 前后跳
[[motion_ids]]
motion_id = 7
map  = [11, 1]   
pre_motion = [1, 3]
post_motion = [1, 3]

# 恢复站立
[[motion_ids]]
motion_id = 8
map  = [12, 0]   
pre_motion = [1, 3]
post_motion = [1, 3]

# 向左打滚一圈
[[motion_ids]]
motion_id = 9
map  = [12, 17]  
pre_motion = [1, 3]
post_motion = [1, 3]

# 作揖
[[motion_ids]]
motion_id = 10
map = [64, 0]   
pre_motion = [1, 3]
post_motion = [1, 3]

# 后空翻
[[motion_ids]]
motion_id = 11
map = [5, 0]    
pre_motion = [1, 3]
post_motion = [1, 3]

# 慢走
[[motion_ids]]
motion_id = 12
map = [11, 20]  
pre_motion = [1, 3]
post_motion = [1, 3]

# 慢走
[[motion_ids]]
motion_id = 13
map = [11, 21]  
pre_motion = [1, 3]
post_motion = [1, 3]

# 慢走
[[motion_ids]]
motion_id = 14
map = [11, 22]  
pre_motion = [2, 5]
post_motion = [2, 5]

# 慢走
[[motion_ids]]
motion_id = 15
map = [11, 23]  
pre_motion = [2, 5]
post_motion = [2, 5]

# 慢走
[[motion_ids]]
motion_id = 16
map = [11, 24]  
pre_motion = [2, 5]
post_motion = [2, 5]

# 慢走
[[motion_ids]]
motion_id = 17
map = [11, 25]  
pre_motion = [2, 5]
post_motion = [2, 5]

# 慢走
[[motion_ids]]
motion_id = 18
map = [11, 26]  
pre_motion = [2, 5]
post_motion = [2, 5]