# motion_id = [mode, gait_id]
0  = [0, 0]    # OFF，即停
1  = [3, 3]    # 力控姿态,保证崎岖地面能够站立
2  = [7, 0]    # 高阻尼趴下
3  = [11, 3]   # 自变频行走
4  = [11, 4]   # 遛狗
5  = [11, 5]   # 快跑
6  = [11, 2]   # 四足小跳
7  = [11, 1]   # 前后跳
8  = [12, 0]   # 恢复站立
9  = [12, 17]  # 向左打滚一圈
10 = [64, 0]   # 作揖
11 = [5, 0]    # 后空翻
12 = [11, 20]  # 慢走
13 = [11, 21]  # 慢走
14 = [11, 22]  # 慢走
15 = [11, 23]  # 慢走
16 = [11, 24]  # 慢走
17 = [11, 25]  # 慢走
18 = [11, 26]  # 慢走